# Generated by Django 4.2.21 on 2026-08-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cuisine', models.CharField(default='Any', max_length=100)),
                ('time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('servings', models.PositiveIntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=4.5)),
                ('emoji', models.CharField(default='🍽️', max_length=10)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('nutrition', models.JSONField(default=dict, help_text='{"protein": "20g", "carbs": "30g", "fat": "10g", "fiber": "5g"}')),
                ('is_popular', models.BooleanField(default=False, help_text='Show on homepage trending section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Saved Recipe',
                'verbose_name_plural': 'Saved Recipes',
                'ordering': ['-saved_at'],
                'unique_together': {('recipe', 'session_key')},
            },
        ),
    ]
